### ISSUE TITLE
Has anyone installed it successfully? I encountered an ERROR: Could not install packages due to an OSError

### ISSUE THREAD

**Issue by MXC66ai** [nhussein/promptsmooth#1]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/croot/certifi_1690232220950/work/certifi'
How to solve this error from the requirements.txt, any idea?

**Comment by nhussein** [comment]
I will update the requirements.txt

**Comment by MXC66ai** [comment]
> I will update the requirements.txt

Ok) thanks

**Comment by nhussein** [comment]
requirements.txt is updated now, and repo.
